-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 20:29:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MarketMeals
-- -----------------------------------------------------
-- MarketMeals Project for LaunchCode
-- v1 Created 2/8/18

-- -----------------------------------------------------
-- Schema MarketMeals
--
-- MarketMeals Project for LaunchCode
-- v1 Created 2/8/18
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MarketMeals` DEFAULT CHARACTER SET utf8 ;
USE `MarketMeals` ;

-- -----------------------------------------------------
-- Table `MarketMeals`.`farmer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketMeals`.`farmer` ;

CREATE TABLE IF NOT EXISTS `MarketMeals`.`farmer` (
  `FarmerID` INT NOT NULL AUTO_INCREMENT,
  `FarmerName` NVARCHAR(255) NOT NULL,
  PRIMARY KEY (`FarmerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MarketMeals`.`prodcat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketMeals`.`prodcat` ;

CREATE TABLE IF NOT EXISTS `MarketMeals`.`prodcat` (
  `ProdCatID` INT NOT NULL AUTO_INCREMENT,
  `ProdCatName` NVARCHAR(255) NOT NULL,
  PRIMARY KEY (`ProdCatID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MarketMeals`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketMeals`.`product` ;

CREATE TABLE IF NOT EXISTS `MarketMeals`.`product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `ProductName` NVARCHAR(255) NOT NULL,
  `Product_ProdCatID` INT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `ProdCatID_idx` (`Product_ProdCatID` ASC),
  CONSTRAINT `Product_ProdCatID`
    FOREIGN KEY (`Product_ProdCatID`)
    REFERENCES `MarketMeals`.`prodcat` (`ProdCatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MarketMeals`.`market`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketMeals`.`market` ;

CREATE TABLE IF NOT EXISTS `MarketMeals`.`market` (
  `MarketID` INT NOT NULL AUTO_INCREMENT,
  `MarketName` NVARCHAR(255) NOT NULL,
  `MarketAddress1` NVARCHAR(255) NULL,
  `MarketAddress2` NVARCHAR(255) NULL,
  `MarketCity` NVARCHAR(255) NULL,
  `MarketState` CHAR(2) NULL,
  `MarketZip` CHAR(5) NOT NULL,
  PRIMARY KEY (`MarketID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MarketMeals`.`marketday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketMeals`.`marketday` ;

CREATE TABLE IF NOT EXISTS `MarketMeals`.`marketday` (
  `MarketDayID` INT NOT NULL AUTO_INCREMENT,
  `MarketDayDate` DATE NOT NULL,
  `MarketDay_MarketID` INT NULL,
  `MarketDay_FarmerID` INT NULL,
  `MarketDay_ProductID` INT NULL,
  PRIMARY KEY (`MarketDayID`),
  INDEX `FarmerID_idx` (`MarketDay_FarmerID` ASC),
  INDEX `ProductID_idx` (`MarketDay_ProductID` ASC),
  INDEX `MarketID_idx` (`MarketDay_MarketID` ASC),
  CONSTRAINT `MarketDay_MarketID`
    FOREIGN KEY (`MarketDay_MarketID`)
    REFERENCES `MarketMeals`.`market` (`MarketID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MarketDay_FarmerID`
    FOREIGN KEY (`MarketDay_FarmerID`)
    REFERENCES `MarketMeals`.`farmer` (`FarmerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MarketDay_ProductID`
    FOREIGN KEY (`MarketDay_ProductID`)
    REFERENCES `MarketMeals`.`product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MarketMeals`.`recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketMeals`.`recipe` ;

CREATE TABLE IF NOT EXISTS `MarketMeals`.`recipe` (
  `RecipeID` INT NOT NULL AUTO_INCREMENT,
  `RecipeName` NVARCHAR(255) NOT NULL,
  `RecipeDirections` TEXT NULL,
  PRIMARY KEY (`RecipeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MarketMeals`.`recipeproduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketMeals`.`recipeproduct` ;

CREATE TABLE IF NOT EXISTS `MarketMeals`.`recipeproduct` (
  `RecipeID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `RecipeAmountRequired` NVARCHAR(255) NULL,
  INDEX `RecipeID_idx` (`RecipeID` ASC),
  INDEX `ProductID_idx` (`ProductID` ASC),
  CONSTRAINT `RecipeID`
    FOREIGN KEY (`RecipeID`)
    REFERENCES `MarketMeals`.`recipe` (`RecipeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProductID`
    FOREIGN KEY (`ProductID`)
    REFERENCES `MarketMeals`.`product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `MarketMeals` ;

-- -----------------------------------------------------
-- Placeholder table for view `MarketMeals`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MarketMeals`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `MarketMeals`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `MarketMeals`.`view1` ;
DROP TABLE IF EXISTS `MarketMeals`.`view1`;
USE `MarketMeals`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
